export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const UPDATE_FNAME='UPDATE_FNAME';
export const UPDATE_LNAME='UPDATE_LNAME';
export const UPDATE_BOTH_FL_NAME = 'UPDATE_BOTH_FL_NAME';